//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using UnityEditor;

[Serializable]
public class UPALayer : ScriptableObject
{
	[SerializeField]
    public int z = 0;
    public float alpha = 1f;
    public string name;
	[NonSerialized]
    public Texture2D image;

    public UPALayer()
    {
    }

	public UPALayer(int w, int h)
	{
		init (w, h);
	}

    public void init(int w, int h)
    {
        name = UPAEditorWindow.CurrentImg.GetDefaultLayerName();


        image = new Texture2D(w, h);
        image.filterMode = FilterMode.Point;

        // Set all pixels to an alpha of 0
        for (int x = 0; x < w; x++)
        {
            for (int y = 0; y < h; y++)
            {
                image.SetPixel(x, y, Color.clear);
            }
        }
        image.Apply();

        EditorUtility.SetDirty(this);
    }

    public void Save()
    {
        UPASession.SaveLayer(this);
    }

    internal void LoadImage()
    {
        image = UPASession.LoadLayerImage(name);
    }
}

